import type { Author } from './types'

export const SAMPLE_AUTHORS: Author[] = [
  {
    id: 'author-james',
    name: "James O'Connor",
    bio: 'F1 correspondent and chief editor at The Fastest Sector. Covers team strategy, driver moves, and the politics behind the paddock.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    twitter: 'https://x.com',
    instagram: 'https://instagram.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'author-senjuti',
    name: 'Senjuti Jash',
    bio: 'Technical analyst covering regulation changes, aerodynamic developments, and the engineering side of Formula 1.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
    twitter: 'https://x.com',
    instagram: 'https://instagram.com',
    linkedin: '',
  },
  {
    id: 'author-laura',
    name: 'Laura Schanz',
    bio: 'Williams F1 and driver market specialist. Tracks career moves, contract negotiations, and engineering talent across the grid.',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face',
    twitter: 'https://x.com',
    instagram: '',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'author-divisha',
    name: 'Divisha Rai',
    bio: 'Formula E and results correspondent. Delivers race breakdowns, standings, and data-driven post-race analysis.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face',
    twitter: 'https://x.com',
    instagram: 'https://instagram.com',
    linkedin: '',
  },
  {
    id: 'author-yixing',
    name: 'Yi Xing Lim',
    bio: 'Feeder series and F1 Academy writer. Covers the next generation of motorsport talent from karting to the top step.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face',
    twitter: '',
    instagram: 'https://instagram.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'author-doris',
    name: 'Doris Ivandic',
    bio: 'Opinion and long-form writer exploring the culture, ethics, and human stories within professional motorsport.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face',
    twitter: 'https://x.com',
    instagram: '',
    linkedin: '',
  },
  {
    id: 'author-editorial',
    name: 'Editorial Staff',
    bio: 'The collective voice of The Fastest Sector team, bringing you breaking news, race updates, and exclusive stories.',
    avatar: '',
    twitter: '',
    instagram: '',
    linkedin: '',
  },
]
