import type { Article } from './types'

const now = Date.now()
const hour = 3600000
const day = 86400000

export const SAMPLE_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'The End of an Era: Verstappen and Lambiase to Split After 2027',
    slug: 'verstappen-lambiase-split-2027',
    excerpt: 'After speculation about Lambiase leaving Red Bull Racing at the end of the 2027 season, he will join McLaren as Chief Racing Officer, marking the end of one of F1\'s most successful driver-engineer partnerships.',
    content: '<p>After speculation about Lambiase leaving Red Bull Racing at the end of the 2027 season, he will join McLaren as Chief Racing Officer.</p><p>The partnership between Max Verstappen and Gianpiero Lambiase has been one of the defining relationships in modern Formula 1. Together, they have navigated the highs of championship victories and the lows of challenging seasons.</p><p>Respected Dutch outlet De Telegraaf first reported the news, which was subsequently confirmed by McLaren. The move continues McLaren\'s aggressive strategy of recruiting top talent from rival teams.</p><h2>A Partnership for the Ages</h2><p>Since joining forces, Verstappen and Lambiase have developed a communication style that has become iconic in the sport. Their radio exchanges, often filled with technical precision and occasional humor, have been a hallmark of Red Bull\'s success.</p><p>The decision marks a significant shift in the competitive landscape of Formula 1, with McLaren continuing to strengthen their position as championship contenders.</p>',
    featuredImage: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&h=500&fit=crop',
    category: 'formula-1',
    tags: ['verstappen', 'lambiase', 'red-bull', 'mclaren'],
    author: 'James O\'Connor',
    status: 'published',
    featured: true,
    createdAt: now - 4 * hour,
    updatedAt: now - 4 * hour,
    publishedAt: now - 4 * hour,
  },
  {
    id: '2',
    title: 'Potential Changes to F1 2026 Regulations: What Was Thursday\'s Meeting with the FIA All About?',
    slug: 'f1-2026-regulations-fia-meeting',
    excerpt: 'With F1 entering a month-long break following the Japanese GP, the FIA and technical experts from the sport\'s key stakeholders held a critical meeting in London on April 9.',
    content: '<p>With F1 entering a month-long break following the Japanese GP, the FIA and technical experts from the sport\'s key stakeholders held a critical meeting—the first of several—in London on April 9 to potentially revise the contentious 2026 technical regulations.</p><p>The introduction of the new power units and chassis has undoubtedly produced more on-track action than many anticipated, but concerns remain about the balance between electrical and combustion power delivery.</p><h2>Key Discussion Points</h2><p>Sources indicate that the primary focus of Thursday\'s meeting was on energy management systems and the deployment strategies that teams have struggled to optimize in the opening races.</p>',
    featuredImage: 'https://images.unsplash.com/photo-1504817343863-5092a923803e?w=800&h=500&fit=crop',
    category: 'formula-1',
    tags: ['fia', 'regulations', '2026'],
    author: 'Senjuti Jash',
    status: 'published',
    featured: false,
    createdAt: now - 6 * hour,
    updatedAt: now - 6 * hour,
    publishedAt: now - 6 * hour,
  },
  {
    id: '3',
    title: 'Dan Milner Joins Williams F1 Team as Chief Engineer of Vehicle Technology',
    slug: 'dan-milner-williams-chief-engineer',
    excerpt: 'After 14 years with Mercedes F1 Team, Dan Milner joined Williams F1 Team as Chief Engineer of Vehicle Technology, bringing Championship-winning experience.',
    content: '<p>After 14 years with Mercedes F1 Team, Dan Milner joined Williams F1 Team as Chief Engineer of Vehicle Technology. Milner brings Championship-winning experience from Brackley, where he worked for Honda and Brawn stretching across Research & Development and powertrains, over to Grove.</p><h2>Championship-winning experience</h2><p>Milner\'s appointment is the latest in a series of high-profile signings by Williams as they continue their rebuilding project under new ownership.</p>',
    featuredImage: 'https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?w=800&h=500&fit=crop',
    category: 'formula-1',
    tags: ['williams', 'mercedes', 'milner'],
    author: 'Laura Schanz',
    status: 'published',
    featured: false,
    createdAt: now - 8 * hour,
    updatedAt: now - 8 * hour,
    publishedAt: now - 8 * hour,
  },
  {
    id: '4',
    title: 'There Are Limits Even in Formula 1',
    slug: 'limits-in-formula-1',
    excerpt: 'The 2026 season had just begun to make sense. Then it stopped. Two races were removed from the calendar, sending shockwaves through the paddock.',
    content: '<p>The 2026 season had just begun to make sense. Then it stopped. Two races were removed from the calendar, sending shockwaves through the paddock and leaving teams scrambling to adjust their logistics and development schedules.</p><p>The decision, announced without much warning, has raised questions about the sustainability of a 24-race calendar and the toll it takes on everyone involved in the sport.</p>',
    featuredImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=500&fit=crop',
    category: 'opinion',
    tags: ['f1', 'calendar', 'opinion'],
    author: 'Editorial Staff',
    status: 'published',
    featured: false,
    createdAt: now - 5 * day,
    updatedAt: now - 5 * day,
    publishedAt: now - 5 * day,
  },
  {
    id: '5',
    title: 'Taylor Barnard: Rising Star in a Vanishing Seat',
    slug: 'taylor-barnard-rising-star',
    excerpt: 'Taylor Barnard\'s career in Formula E hasn\'t followed a linear trajectory from the start. Going from Formula 2 to the electric series presented unique challenges.',
    content: '<p>Taylor Barnard\'s career in Formula E hasn\'t followed a linear trajectory from the start. Going from Formula 2 to the electric series presented unique challenges that the young British driver has had to overcome.</p><p>With limited seats available in the all-electric championship, Barnard has shown remarkable adaptability and speed, marking himself as one to watch for the future.</p>',
    featuredImage: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&h=500&fit=crop',
    category: 'formula-e',
    tags: ['barnard', 'formula-e'],
    author: 'Divisha Rai',
    status: 'published',
    featured: false,
    createdAt: now - 5 * day,
    updatedAt: now - 5 * day,
    publishedAt: now - 5 * day,
  },
  {
    id: '6',
    title: 'Alba Larsen – One to Watch',
    slug: 'alba-larsen-one-to-watch',
    excerpt: 'Over the course of its four seasons, the F1 Academy grid has featured a number of drivers. Drivers can compete for no longer than 2 years, but new opportunities arise for those who win the title.',
    content: '<p>Over the course of its four seasons, the F1 Academy grid has featured a number of drivers. Drivers can compete for no longer than 2 years, but new opportunities arise for those who win the title in their first season.</p><p>Alba Larsen has emerged as one of the most exciting talents in the 2026 grid, combining raw speed with tactical intelligence that belies her years of experience.</p>',
    featuredImage: 'https://images.unsplash.com/photo-1504817343863-5092a923803e?w=800&h=500&fit=crop',
    category: 'f1-academy',
    tags: ['f1-academy', 'larsen'],
    author: 'Yi Xing Lim',
    status: 'published',
    featured: true,
    createdAt: now - 2 * day,
    updatedAt: now - 2 * day,
    publishedAt: now - 2 * day,
  },
  {
    id: '7',
    title: 'F2 Replaces Cancelled Middle East Rounds with Miami and Canadian GP',
    slug: 'f2-replaces-middle-east-rounds',
    excerpt: 'The revised FIA F2 2026 calendar adds Miami and Canadian GP to replace the cancelled Middle East rounds, maintaining a full racing schedule.',
    content: '<p>The revised FIA Formula 2 2026 calendar has been announced, with the Miami and Canadian Grand Prix weekends replacing the previously cancelled Middle East rounds.</p><p>The changes ensure that the F2 championship maintains its planned number of events, giving young drivers the maximum opportunity to showcase their talents on the road to Formula 1.</p>',
    featuredImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=500&fit=crop',
    category: 'feeder-series',
    tags: ['f2', 'calendar'],
    author: 'Yi Xing Lim',
    status: 'published',
    featured: false,
    createdAt: now - 10 * hour,
    updatedAt: now - 10 * hour,
    publishedAt: now - 10 * hour,
  },
  {
    id: '8',
    title: 'Aston Martin F1 Welcomes Two New Karting Talents to Driver Academy',
    slug: 'aston-martin-driver-academy',
    excerpt: 'Aston Martin F1 welcomes Ava Lawrence and Roland Nagy to its Driver Academy programme, reflecting the team\'s commitment to nurturing the next generation.',
    content: '<p>Aston Martin F1 welcomes two young talents, Ava Lawrence and Roland Nagy, to its Driver Academy programme. The expansion of the academy lineup reflects the team\'s ongoing commitment to nurturing the next generation of motorsport stars.</p>',
    featuredImage: 'https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?w=800&h=500&fit=crop',
    category: 'formula-1',
    tags: ['aston-martin', 'academy'],
    author: 'Yi Xing Lim',
    status: 'published',
    featured: false,
    createdAt: now - 12 * hour,
    updatedAt: now - 12 * hour,
    publishedAt: now - 12 * hour,
  },
  {
    id: '9',
    title: 'Lola Yamaha Formula E Drivers Reflect on Missed Opportunity in Madrid',
    slug: 'lola-yamaha-formula-e-madrid',
    excerpt: 'The Lola Yamaha Formula E team reflects on a weekend in Madrid that promised much but ultimately delivered less than expected.',
    content: '<p>The Lola Yamaha Formula E team reflects on a weekend in Madrid that promised much but ultimately delivered less than expected. Despite showing strong pace in practice and qualifying, race day proved challenging.</p>',
    featuredImage: 'https://images.unsplash.com/photo-1504817343863-5092a923803e?w=800&h=500&fit=crop',
    category: 'formula-e',
    tags: ['formula-e', 'lola', 'yamaha', 'madrid'],
    author: 'Divisha Rai',
    status: 'published',
    featured: false,
    createdAt: now - 15 * hour,
    updatedAt: now - 15 * hour,
    publishedAt: now - 15 * hour,
  },
  {
    id: '10',
    title: 'Exclusive: Martins Looking for a True Opportunity in Formula E',
    slug: 'martins-formula-e-opportunity',
    excerpt: 'In an exclusive interview, Victor Martins discusses his ambitions and the challenges of finding a competitive seat in the all-electric championship.',
    content: '<p>In an exclusive interview, Victor Martins discusses his ambitions and the challenges of finding a competitive seat in the all-electric championship. The former Formula 2 front-runner is determined to prove himself given the right machinery.</p>',
    featuredImage: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&h=500&fit=crop',
    category: 'exclusive',
    tags: ['exclusive', 'martins', 'formula-e'],
    author: 'Doris Ivandic',
    status: 'published',
    featured: false,
    createdAt: now - 7 * day,
    updatedAt: now - 7 * day,
    publishedAt: now - 7 * day,
  },
]
